superpixel_depth_segmentation_node:
  ros__parameters:
    use_sim_time: true

    depth_image_topic: /floor_image
    normal_image_topic: /floor_normals

    k_c: 256
    v_fov: 60.0
    v_offset: 0.0

    num_dilation_iterations: 0
    kernel_radius: 1

    num_iterations: 5
    num_superpixels: 150
    warm_start: false
    constraint: false
    ransac: true
    snapping: false

    w_normal: 1.0
    w_pos: 1.0
    w_compact: 1.0

    ransac_K: 10
    ransac_N: 25
    ransac_T: 0.01